name: Release crypto-icons package

on:
  push:
    branches:
      - main
    paths: 
      - "lib/**"

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lib/
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: pnpm install
        
      - name: Setup node to publish in Github package
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Publish package 
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
